pull_request_rules:
  - name: automatic merge on CI success and review
    conditions:
      - base=master
      - author=thanodnl
      - status-success=continuous-integration/travis-ci/pr
      - label=ready-to-merge
    actions:
      merge:
        method: merge
        strict: smart
